### ISSUE TITLE
NameError: name 'os' is not defined after last commit

### ISSUE THREAD

**Issue by OValete** [0cc4m/KoboldAI#26]
Traceback (most recent call last):
  File "aiserver.py", line 598, in <module>
    koboldai_vars = koboldai_settings.koboldai_vars(socketio)
  File "/kaggle/tmp/KoboldAI/koboldai_settings.py", line 99, in __init__
    self._system_settings = system_settings(socketio, self)
  File "/kaggle/tmp/KoboldAI/koboldai_settings.py", line 1309, in __init__
    import gptq
  File "/kaggle/tmp/KoboldAI/runtime/envs/koboldai/lib/python3.8/site-packages/gptq/__init__.py", line 1, in <module>
    from . import gptj, gptneox, llama, opt, offload
  File "/kaggle/tmp/KoboldAI/runtime/envs/koboldai/lib/python3.8/site-packages/gptq/gptj.py", line 9, in <module>
    from .gptq import GPTQ
  File "/kaggle/tmp/KoboldAI/runtime/envs/koboldai/lib/python3.8/site-packages/gptq/gptq.py", line 8, in <module>
    from .modelutils import GPTQVERSION
  File "/kaggle/tmp/KoboldAI/runtime/envs/koboldai/lib/python3.8/site-packages/gptq/modelutils.py", line 9, in <module>
    GPTQVERSION = int(os.environ.get("GPTQVERSION", 1))
NameError: name 'os' is not defined

**Comment by 0cc4m** [comment]
Thank you for the report, there was indeed a problem with the Linux wheel. I forgot to recompile, I think. I uploaded a new version, can you check if it fixes the problem? Rerunning `install_requirements.sh` should pull it.

**Comment by OValete** [comment]
It worked, thanksss ;D
