### ISSUE TITLE
ImportError: cannot import name 'url_quote' from 'werkzeug.urls'

### ISSUE THREAD

**Issue by axshb** [0cc4m/KoboldAI#75]
Trying to do a fresh install after deleting my old copy. Here is the error:

```
The system cannot find the file specified.
Runtime launching in B: drive mode
Traceback (most recent call last):
  File "aiserver.py", line 67, in <module>
    from utils import debounce
  File "D:\KoboldAI\utils.py", line 192, in <module>
    from flask_socketio import emit
  File "B:\python\lib\site-packages\flask_socketio\__init__.py", line 18, in <module>
    import flask
  File "B:\python\lib\site-packages\flask\__init__.py", line 5, in <module>
    from .app import Flask as Flask
  File "B:\python\lib\site-packages\flask\app.py", line 30, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (B:\python\lib\site-packages\werkzeug\urls.py)
```

Steps to reproduce are the same as the installation instructions on the readme (Windows 10, Nvidia GPU, B: drive mode):

1. `git clone https://github.com/0cc4m/KoboldAI -b latestgptq --recurse-submodules`
2. `cd KoboldAI`
3. `install_requirements.bat`
4. Launch 'play.bat'

Might be an issue with the September 30th release of Werkzeug 3.0.0? Not sure. Looks like[ this pull request](https://github.com/0cc4m/KoboldAI/pull/74) confirms it though.

**Comment by c-dante** [comment]
https://github.com/0cc4m/KoboldAI/pull/74/files
