### ISSUE TITLE
./play-rocm.sh gptq error fedora 39

### ISSUE THREAD

**Issue by Korpyz** [0cc4m/KoboldAI#76]
./play-rocm.sh 
Colab Check: False, TPU: False
Traceback (most recent call last):
  File "aiserver.py", line 604, in <module>
    from modeling.inference_models.hf_torch_4bit import load_model_gptq_settings
  File "/home/madrugada/KoboldAI/modeling/inference_models/hf_torch_4bit.py", line 31, in <module>
    import gptq
ModuleNotFoundError: No module named 'gptq'

**Comment by 0cc4m** [comment]
This repo is out of date, please use https://github.com/henk717/KoboldAI/
